name: autorevive
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router:
  flutter_svg: ^2.0.16
  lottie:
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  country_state_city_pro: ^0.0.6
  dropdown_button2: ^2.3.9

  google_maps_flutter: ^2.1.1
  permission_handler:
  location:
#  geolocator: ^9.0.1
  geocoding: ^2.1.0


  internet_connection_checker_plus: ^2.5.2
  connectivity_plus: ^6.1.2


  shared_preferences: ^2.5.3
  timeago: ^3.6.1
  get: ^4.6.6
  mime_type: ^1.0.1
  file_picker: ^10.1.2
  flutter_spinkit: ^5.2.1

  flutter_switch: ^0.3.2

  chat_bubbles: ^1.6.0
  country_code_picker: ^3.3.0
  custom_rating_bar: ^3.0.0
  toastification:
  quickalert: ^1.1.0
  location_picker_text_field:
  country_pickers: ^3.0.1
  socket_io_client:
  flutter_polyline_points: ^2.1.0
  flutter_local_notifications: ^18.0.1
  firebase_messaging:
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  flutter_widget_from_html:
  webview_flutter: ^4.13.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  flutter_gen_runner: null
  flutter_launcher_icons:

flutter_gen:
  output: lib/global/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true
    #===========>>>>>>>>>> Flutter Gen Code ==============>>>>>>>>>>>
    # dart pub global activate flutter_gen
    # flutter pub run build_runner build --delete-conflicting-outputs
#    dart run build_runner build


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/
     - assets/lottie/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
     - family: Outfit
       fonts:
         - asset: assets/fonts/Outfit.ttf

#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700


